module.exports = {
  purge: ['./components/**/*', './pages/**/*', './hooks/**/*'],
  theme: {
    extend: {
      colors: {
        background: 'var(--color-background)',
        skeleton: 'var(--color-skeleton)',
        gradient100: 'var(--color-gradient100)',
        gradient200: 'var(--color-gradient200)',
        gradient300: 'var(--color-gradient300)',
        paper: 'var(--color-paper)',
        primaryText: 'var(--color-primaryText)',
        secondaryText: 'var(--color-secondaryText)',
        divider: 'var(--color-divider)',
        yellow: 'var(--color-yellow)',
        blue: 'var(--color-blue)',
        bioret: 'var(--color-bioret)',
        red: 'var(--color-red)',
        green: 'var(--color-green)',
        opacityYellow: 'var(--color-opacityYellow)',
        opacityBlue: 'var(--color-opacityBlue)',
        opacityBioret: 'var(--color-opacityBioret)',
        opacityRed: 'var(--color-opacityRed)',
        opacityGreen: 'var(--color-opacityGreen)',
        border: 'var(--color-border)',
        reactHook: 'var(--color-reactHook)',
        redux: 'var(--color-redux)',
        localStorage: 'var(--color-localStorage)',
        typeScript: 'var(--color-typeScript)',
        gatsby: 'var(--color-gatsby)',

        materialUi: 'var(--color-materialUi)',
        nextJs: 'var(--color-nextJs)',
        styledComponents: 'var(--color-styledComponents)',
        scss: 'var(--color-scss)',
        graphQl: 'var(--color-graphQl)',
        contentful: 'var(--color-contentful)',
        tailwind: 'var(--color-tailwind)',
        inner: 'var(--color-inner)',
      },
      fontFamily: {
        body: ['Montserrat', 'Sans-serif'],
        display: ['Rubik', 'Sans-serif'],
      },
      fontWeight: {
        light: 300,
        normal: 400,
        bold: 700,
      },
      screens: {
        mobile: { max: '767px' },
        tablet: { min: '768px', max: '919px' },
        desktop: { min: '920px' },
      },
    },
  },
  variants: {
    backgroundColor: ['responsive', 'hover', 'focus', 'group-hover'],
    textColor: ['responsive', 'hover', 'focus', 'group-hover'],
    textDecoration: ['responsive', 'hover', 'focus', 'active', 'group-hover'],
  },
  plugins: [],
};
